base_url = "https://267services.com"

compile_sass = true
build_search_index = false

title = "267 Services"
description = "Enterprise Consulting Services"
author = "267 Services"

[markdown]
highlight_code = true
highlight_theme = "gray-matter-dark"
